Repository Team-ZeroSugar/TIG-iOS, pull requests merged in 2024-09, with the labels that each got.

#35 Refactor/#34 DateComponents
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/Timeline/TimelineView.swift
Labels: 🐞 버그, ♻️ 리펙토링

#37 [Feat] HomeView에 DailyContent 데이터 적용
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/App/DIContainer.swift
  TIG/TIG/Extension/Date+Ext.swift
  TIG/TIG/Extension/DateComponents+Ext.swift
  TIG/TIG/Feature/Home/HomeView.swift
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Model/DTO/DailyContentSD.swift
  TIG/TIG/Model/DTO/TimelineSD.swift
  TIG/TIG/Model/DTO/WeeklyRepeatSD.swift
  TIG/TIG/Presentaion/Home/HomeView.swift
  TIG/TIG/Repository/DefaultDailyContentRepository.swift
  TIG/TIG/Repository/DefaultWeeklyRepeatRepository.swift
  TIG/TIG/Repository/Storage/SwiftDataStorage.swift
Labels: 🛠️ 기능

#42 Feature/#38 Timeline Swift Data
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/Feature/Home/AnnounceView.swift
  TIG/TIG/Feature/Home/HomeView.swift
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/More/WeeklyRepeatView.swift
  TIG/TIG/Feature/Home/Timeline/TimelineView.swift
Labels: 🛠️ 기능

#43 Feature/#39 onboarding view
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/App/TIGApp.swift
  TIG/TIG/Constant/UserDefaultsKey.swift
  TIG/TIG/Extension/Int+Ext.swift
  TIG/TIG/Feature/Onboarding/CustomWheelPicker.swift
  TIG/TIG/Feature/Onboarding/OnboardingView.swift
  TIG/TIG/Resource/Assets.xcassets/circles.imageset/Contents.json
  TIG/TIG/Resource/Assets.xcassets/circles.imageset/Group 48097042.png
  TIG/TIG/Resource/Assets.xcassets/circles.imageset/circle.png
  TIG/TIG/Resource/Assets.xcassets/onboarding-first.imageset/Contents.json
  TIG/TIG/Resource/Assets.xcassets/onboarding-first.imageset/onboarding-first.png
  TIG/TIG/Resource/Assets.xcassets/onboarding-second.imageset/Contents.json
  TIG/TIG/Resource/Assets.xcassets/onboarding-second.imageset/Group 48097039.png
  TIG/TIG/Resource/Assets.xcassets/onboarding-second.imageset/onboarding-second.png
  TIG/TIG/Resource/Assets.xcassets/onboarding-third.imageset/Contents.json
  TIG/TIG/Resource/Assets.xcassets/onboarding-third.imageset/Group 48097037.png
  TIG/TIG/Resource/Assets.xcassets/onboarding-third.imageset/onboarding-third.png
Labels: 🛠️ 기능

#46 Feature/#44 Timeline Userdefaults
  TIG/TIG/Extension/Date+Ext.swift
  TIG/TIG/Feature/Home/AnnounceView.swift
  TIG/TIG/Feature/Home/HomeView.swift
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/Timer/TimerView.swift
Labels: 🛠️ 기능

#48 Feature/#45 setting view sleep time
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/App/TIGApp.swift
  TIG/TIG/Extension/DateComponents+Ext.swift
  TIG/TIG/Extension/Int+Ext.swift
  TIG/TIG/Feature/Component/CustomActionSheet.swift
  TIG/TIG/Feature/Component/CustomWheelPicker.swift
  TIG/TIG/Feature/Home/HomeView.swift
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/More/SettingView.swift
  TIG/TIG/Feature/Home/More/SettingViewModel.swift
  TIG/TIG/Feature/Onboarding/OnboardingView.swift
  TIG/TIG/Repository/DefaultDailyContentRepository.swift
Labels: 🛠️ 기능

#51 Feature/#47 TimeView Data
  TIG/TIG/Extension/Int+Ext.swift
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/Timer/TimerView.swift
Labels: 🛠️ 기능

#52 Feature/#50 Repeat Scheldule
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/More/WeeklyRepeatView.swift
  TIG/TIG/Feature/Home/Timeline/TimelineView.swift
Labels: 🛠️ 기능

#57 Fix/#56 modify persistence model
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/App/Info.plist
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Model/DTO/WeeklyRepeatSD.swift
  TIG/TIG/Model/Persistence/DailyContentSD.swift
  TIG/TIG/Model/Persistence/TimelineSD.swift
  TIG/TIG/Model/Persistence/WeeklyRepeatSD.swift
  TIG/TIG/Repository/TestData.swift
Labels: 🐞 버그

#58 Fix/#53 Save without Edit Completion Bug
  TIG/TIG.xcodeproj/project.pbxproj
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/More/WeeklyRepeatView.swift
  TIG/TIG/Feature/Home/Timeline/TimelineView.swift
  TIG/TIG/Model/Entitiy/Timeline.swift
Labels: 🐞 버그

#55 Refactor/#54 TimerView 코드 수정
  TIG/TIG/Feature/Home/HomeViewModel.swift
  TIG/TIG/Feature/Home/Timer/TimerView.swift
Labels: ♻️ 리펙토링
